import '@testing-library/jest-dom';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  ns: ['translation'],
  defaultNS: 'translation',
  resources: {
    en: {
      translation: {
        common: {
          loading: 'Loading',
          error: 'Error',
          cancel: 'Cancel',
          save: 'Save',
          delete: 'Delete',
          back: 'Back',
          create: 'Create',
          close: 'Close',
          comingSoon: 'Soon',
          saving: 'Saving...',
        },
        auth: {
          signIn: 'Sign in',
          signInWithGoogle: 'Sign in with Google',
          register: 'Register',
          createAccount: 'Create account',
          noAccount: 'No account?',
          hasAccount: 'Already have an account?',
          email: 'Email',
          password: 'Password',
          name: 'Name',
          emailPlaceholder: 'you@example.com',
          passwordPlaceholder: '••••••',
          namePlaceholder: 'Your name',
          signInToContinue: 'Sign in to continue.',
          signOut: 'Sign out',
        },
        family: {
          createTitle: 'Create a Family',
          createSubtitle: 'Set up your family space to get started.',
          familyName: 'Family Name',
          familyNamePlaceholder: 'The Smiths',
          icon: 'Icon',
          creating: 'Creating...',
          createButton: 'Create Family',
          backToFamilies: 'Back to my families',
          newFamily: 'New Family',
          settings: 'Settings',
          noPages: 'No pages yet',
          createFirstPage: 'Create your first page to organize your family.',
          members: 'Members',
        },
        invite: {
          joining: 'Joining family...',
          success: 'Welcome to {{familyName}}!',
          invalidToken: 'Invite not valid',
          goHome: 'Go Home',
          loginRequired: 'You must be logged in to join this family.',
        },
        pages: {
          newPage: '+ New Page',
          calendar: 'Calendar',
          createTitle: 'New page',
          titleLabel: 'Title',
          titlePlaceholder: 'My new page',
          typeLabel: 'Type',
          listType: 'List',
          listTypeDesc: 'Checklist, grocery, tasks',
          eventsType: 'Events',
          eventsTypeDesc: 'Upcoming events',
          tasksType: 'Tasks',
          tasksTypeDesc: 'Assignable tasks with status',
          apartmentsType: 'Apartments',
          apartmentsTypeDesc: 'Track apartment listings from yad2',
          notFound: 'Page not found',
          notFoundBack: 'Back to family home',
          eventsComingSoon: 'Events page — coming in Phase 3.',
          loadError: 'This page may have been deleted or you may not have access.',
          pages: 'Pages',
          addListBlock: '+ List',
          addTextBlock: '+ Text',
          blockTitlePlaceholder: 'Block title...',
          textBlockPlaceholder: 'Write something...',
        },
        apartments: {
          searchParams: 'Search Filters',
          dealType: 'Deal type',
          rent: 'Rent',
          buy: 'Buy',
          minRooms: 'Min rooms',
          maxRooms: 'Max rooms',
          city: 'City',
          area: 'Area',
          minPrice: 'Min price',
          maxPrice: 'Max price',
          neighbourhood: 'Neighbourhood / street',
          minFloor: 'Min floor',
          maxFloor: 'Max floor',
          keywords: 'Keywords',
          syncNow: 'Sync now',
          syncing: 'Syncing...',
          lastSynced: 'Last synced',
          never: 'Never',
          viewListing: 'View listing',
          markSeen: 'Mark as seen',
          noListings: 'No listings yet',
          noListingsHint: 'Set your search filters and click "Save & Search" to fetch apartments.',
          saveAndSearch: 'Save & Search',
          searching: 'Searching yad2...',
          searchDone: 'Search done ✓',
          searchError: 'Search failed — try again',
          foundNew: 'Found {{count}} new listings!',
          upToDate: 'Up to date — no new listings',
          listingsCount: 'listings',
          parking: 'Parking',
          balcony: 'Balcony',
          elevator: 'Elevator',
          secureRoom: 'Secure room',
          rooms: 'rooms',
          floor: 'Floor',
        },
        tasks: {
          todo: 'To do',
          inProgress: 'In progress',
          done: 'Done',
          addTaskPlaceholder: 'Add task...',
          addTask: 'Add',
          emptyState: 'No tasks yet. Add your first task above.',
          assignTo: 'Assign to...',
          unassign: 'Unassign',
          setDueDate: 'Set due date',
          clearDate: 'Clear date',
          overdue: 'Overdue',
          deleteTask: 'Delete task',
          statusTodo: 'Todo',
          statusInProgress: 'In Progress',
          statusDone: 'Done',
        },
        list: {
          addItemPlaceholder: '+ Add item',
          addItem: 'Add',
          emptyState: 'No items yet.',
          assignTo: 'Assign to',
          unassign: 'Unassign',
          setDueDate: 'Set due date',
          clearDate: 'Clear date',
          overdue: 'overdue',
          deleteItem: 'Delete item',
          editTitle: 'Edit title',
          resetAll: 'Reset all',
          addCategory: '+ Add category',
          categoryPlaceholder: 'Category name...',
          uncategorized: 'General',
          simpleList: 'Simple list',
          categorizedList: 'List by categories',
        },
        calendar: {
          title: 'Calendar',
          today: 'Today',
          newEvent: '+ New Event',
          noEvents: 'No events this month',
          allDay: 'All day',
          createEvent: 'Create Event',
          editEvent: 'Edit Event',
          deleteEvent: 'Delete Event',
          eventTitle: 'Event title',
          description: 'Description',
          startDate: 'Start',
          endDate: 'End',
          save: 'Save',
          cancel: 'Cancel',
          monthNames: ['January','February','March','April','May','June','July','August','September','October','November','December'],
          dayNames: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
          showPast: 'Show past',
          hidePast: 'Hide past',
          noEventsLinked: 'No events linked yet.',
          linkEvent: '+ Link event',
          newLinkedEvent: '+ New event',
          pickEvent: 'Pick an event',
          confirmDelete: 'Delete this event?',
          starts: 'Starts',
          edit: 'Edit',
          reminder: 'Reminder',
          recurrence: 'Repeat',
          recurrenceNone: 'Does not repeat',
          recurrenceDaily: 'Daily',
          recurrenceWeekly: 'Weekly',
          recurrenceMonthly: 'Monthly',
          recurrenceYearly: 'Yearly',
          recurrenceUntil: 'Until',
          recurrenceLabel: 'Repeats {{freq}}',
          editRecurring: 'Edit recurring event',
          editThisOnly: 'This event only',
          editAllEvents: 'All events in series',
          deleteRecurring: 'Delete recurring event',
          deleteThisOnly: 'This event only',
          deleteAllEvents: 'All events in series',
        },
        nav: {
          home: 'Home',
          english: 'English',
          hebrew: 'Hebrew',
          openMenu: 'Open menu',
          closeMenu: 'Close menu',
        },
        search: {
          placeholder: 'Search...',
          pages: 'Pages',
          items: 'Items',
          tasks: 'Tasks',
          events: 'Events',
          noResults: 'No results for "{{q}}"',
          searching: 'Searching...',
        },
        activity: {
          title: 'Activity',
          empty: 'No activity yet',
          loadMore: 'Load more',
          item_added: 'Added "{{itemText}}" to {{pageTitle}}',
          item_checked: 'Checked off "{{itemText}}" in {{pageTitle}}',
          task_created: 'Created task "{{taskTitle}}" in {{pageTitle}}',
          task_status_changed: 'Moved "{{taskTitle}}" to {{status}} in {{pageTitle}}',
          event_created: 'Created event "{{title}}"',
          member_invited: 'Joined the family',
          unknown: 'Unknown activity',
          justNow: 'just now',
          minAgo: '{{count}} min ago',
          hoursAgo: '{{count}} hours ago',
        },
      },
    },
  },
  interpolation: { escapeValue: false },
});
